dev/src/bitnow_client/src/main/java/com/gconsulting/webapp/model/UserView.java
package com.gconsulting.webapp.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;

import com.gsconsulting.bitnow.model.Account;
import com.gsconsulting.bitnow.model.Document;
import com.gsconsulting.bitnow.model.LabelValue;
import com.gsconsulting.bitnow.model.Role;
import com.gsconsulting.bitnow.model.User;

/**
 * This class represents the basic "user" object in AppFuse that allows for
 * authentication and user management. It implements Acegi Security's
 * UserDetails interface.
 *
 * @author <a href="mailto:matt@raibledesigns.com">Matt Raible</a> Updated by
 *         Dan Kibler (dan@getrolling.com) Extended to implement Acegi
 *         UserDetails interface by David Carter david@carter.net
 */
public class UserView implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3099000778199593358L;
	private User user;
	private Set<Role> roles;
	private List<Account> accounts;
	private List<Document> documents;

	/**
	 * Default constructor - creates a new instance with no values set.
	 */
	public UserView() {
	}

	/**
	 * Create a new instance and set the username.
	 *
	 * @param username
	 *            login name for user.
	 */
	public UserView(User user) {
		this.user = user;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public List<Account> getAccounts() {
		return accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}

	public List<Document> getDocuments() {
		return documents;
	}

	public void setDocuments(List<Document> documents) {
		this.documents = documents;
	}

	/**
	 * Convert user roles to LabelValue objects for convenience.
	 *
	 * @return a list of LabelValue objects with role information
	 */
	public List<LabelValue> getRoleList() {
		
		List<LabelValue> userRoles = new ArrayList<LabelValue>();
		if (this.roles != null) {
			for (Role role : roles) {
				// convert the user's roles to LabelValue Objects
				userRoles.add(new LabelValue(role.getName(), role.getName()));
			}
		}
		return userRoles;
	}

	/**
	 * @return GrantedAuthority[] an array of roles.
	 * @see org.springframework.security.core.userdetails.UserDetails#getAuthorities()
	 */
	public Set<GrantedAuthority> getAuthorities() {
		Set<GrantedAuthority> authorities = new LinkedHashSet<GrantedAuthority>();
		authorities.addAll(roles);
		return authorities;
	}

	/**
	 * {@inheritDoc}
	 */
	public boolean equals(Object o) {

		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	public int hashCode() {
		return (user.getUsername() != null ? user.getUsername().hashCode() : 0);
	}

	/**
	 * {@inheritDoc}
	 */
	public String toString() {
		return "";
	}
}

dev/src/bitnow_client/src/main/java/com/gconsulting/webapp/action/MenuController.java
package com.gconsulting.webapp.action;

import java.io.IOException;
import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.gsconsulting.bitnow.model.Role;
import com.gsconsulting.bitnow.model.User;
import com.gsconsulting.bitnow.model.service.UserManager;
import com.gsconsulting.bitnow.model.util.Constants;

@Scope("session")
// @Component("menuController")
@Controller("menuController")
public class MenuController extends BasePage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7204659847632369338L;
	private User user = new User();

	public MenuController() {

		super();
	}

	private void loadUser() {

		if (getRequest().getRemoteUser() != null) {
			user = userManager.getUserByUsername(getRequest().getRemoteUser());
		} else {
			user = null;
		}
		if (user != null) {
			if (user.getUsername() != null) {
				user.setConfirmPassword(user.getPassword());
			}
		}
	}

	@PostConstruct
	public void init() {
		loadUser();
	}

	@Override
	@Autowired
	public void setUserManager(@Qualifier("userManager") UserManager userManager) {
		this.userManager = userManager;
	}

	public void registerUserNewsletter() {
		/*
		 * TODO: Register insterted E-Mail and display message (Optional): send
		 * confirmation email.
		 */
		addFacesMessage("website.home.newsletterOK");
	}

	public boolean getUserLoggedIn() {

		if (user != null) {
			return true;
		} else {
			return false;
		}
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTheme() {

		loadUser();
		return user.getTheme();
	}

	/**
	 * Logout
	 * 
	 * @return
	 */
	public void logout() throws IOException {

		ExternalContext ec = FacesContext.getCurrentInstance()
				.getExternalContext();
		ec.invalidateSession();
		ec.redirect(ec.getRequestContextPath() + "/home");
	}

	public boolean isAdmin() {

		if (user == null) {
			loadUser();
		}
		for (Role role : user.getRoles()) {
			if (role.getName().equalsIgnoreCase(Constants.ADMIN_ROLE)) {
				return true;
			}
		}
		return false;
	}
}

dev/src/bitnow_client/src/main/java/com/gconsulting/webapp/action/SecurityAction.java
package com.gconsulting.webapp.action;

import java.io.IOException;
import java.io.Serializable;

import java.lang.NumberFormatException;

import javax.annotation.PostConstruct;
import javax.servlet.http.HttpServletResponse;

import org.springframework.context.annotation.Scope;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Component;

import com.gsconsulting.bitnow.model.User;
import com.gsconsulting.bitnow.model.service.UserExistsException;
import com.gsconsulting.bitnow.model.util.CryptService;
import com.warrenstrange.googleauth.GoogleAuthenticatorKey;

/**
 * JSF Page class to handle editing a user with a form.
 *
 * @author mraible
 */
@Scope("session")
@Component("securityAction")
public class SecurityAction extends BasePage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7716617831182716060L;
	private User user;
	private GoogleAuthenticatorKey twoFAKey;
	private String twoFALink;
	private String password2FA;
	private String password2FADisable;

	@PostConstruct
	public void init() {

		loadUser();
		init2FA();
	}

	private void init2FA() {

		twoFAKey = CryptService.getKey();
		twoFALink = CryptService.qrURL(
				com.gconsulting.webapp.util.Constants.TWO_FA_ISSUER,
				user.getUsername(), twoFAKey);
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * Enable 2FA
	 * 
	 * @return
	 */
	public String enable2FA() {

		try {
			if (CryptService.authorize(twoFAKey.getKey(), new Integer(
					password2FA))) {
				user.setSecret(twoFAKey.getKey());
				userManager.update(user);
				addFacesMessage("user.saved");
				password2FA = null;
				password2FADisable = null;
				return "security";
			}
		} catch (NumberFormatException e) {
			log.error("Error: " + e.getMessage());
		}
		password2FA = null;
		password2FADisable = null;
		addFacesError("errors.otp");
		return "security";
	}

	/**
	 * Disable 2FA
	 * 
	 * @return
	 */
	public String disable2FA() {

		try {
			log.info("Secret: " + user.getSecret());
			log.info("OTP: " + password2FADisable);
			if (CryptService.authorize(user.getSecret(), new Integer(
					password2FADisable))) {
				user.setSecret("");
				userManager.update(user);
				addFacesMessage("user.saved");
				password2FA = null;
				password2FADisable = null;
				return "security";
			}
		} catch (NumberFormatException e) {
			log.error("Error: " + e.getMessage());
		}
		password2FA = null;
		password2FADisable = null;
		addFacesError("errors.otp");
		return "security";
	}

	public void otpRefresh() {
		log.info("OTP: " + password2FA);
	}

	/**
	 * Reset form
	 * 
	 * @return
	 */
	public String cancel() {

		if (log.isDebugEnabled()) {
			log.debug("Entering 'cancel' method");
		}
		if (!"list".equals(getParameter("from"))) {
			return "home";
		} else {
			return "cancel";
		}
	}

	/**
	 * Load user data
	 * 
	 * @return
	 */
	public String loadUser() {

		user = userManager.getUserByUsername(getRequest().getRemoteUser());
		if (user.getUsername() != null) {
			user.setConfirmPassword(user.getPassword());
		}
		return "security";
	}

	/**
	 * Save a user
	 * 
	 * @return
	 * @throws IOException
	 */
	public String save() throws IOException {

		Integer originalVersion = user.getVersion();
		/*
		 * Check password matches!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		 */
		if (!user.getPassword().equalsIgnoreCase(user.getConfirmPassword())) {
			addFacesError("errors.password.confirmPasswordMismatch");
			return "security";
		}
		try {
			user = userManager.saveUser(user);
		} catch (AccessDeniedException ade) {
			// thrown by UserSecurityAdvice configured in aop:advisor
			// userManagerSecurity
			log.warn(ade.getMessage());
			getResponse().sendError(HttpServletResponse.SC_FORBIDDEN);
			return "security";
		} catch (UserExistsException e) {
			addFacesError("errors.existing.user",
					new Object[] { user.getUsername(), user.getEmail() });
			// reset the version # to what was passed in
			user.setVersion(originalVersion);
			return "security";
		}
		user.setConfirmPassword(user.getPassword());
		addFacesMessage("user.saved");
		// return to main Menu
		return "security";
	}

	/**
	 * Check if 2FA is enabled for this user
	 * 
	 * @return
	 */

	public boolean isTwoFAEnabled() {

		if (user != null) {
			if (user.getSecret() != null) {
				if (user.getSecret().length() > 0) {
					return true;
				}
			}
		}
		return false;
	}

	public String getTwoFAKey() {
		return twoFAKey.getKey();
	}

	public String getTwoFALink() {
		return twoFALink;
	}

	public String getPassword2FA() {
		return password2FA;
	}

	public void setPassword2FA(String password2FA) {
		this.password2FA = password2FA;
	}

	public String getPassword2FADisable() {
		return password2FADisable;
	}

	public void setPassword2FADisable(String password2faDisable) {
		password2FADisable = password2faDisable;
	}
}

dev/src/bitnow_client/src/main/webapp/app/myProfile/logout.jsp
<%@ include file="/common/taglibs.jsp"%>
<%@ page import="org.springframework.security.web.authentication.rememberme.TokenBasedRememberMeServices" %>
<%@ page import="javax.servlet.http.Cookie" %>

<%
if (request.getSession(false) != null) {
    session.invalidate();
}
Cookie terminate = new Cookie(TokenBasedRememberMeServices.SPRING_SECURITY_REMEMBER_ME_COOKIE_KEY, null);
String contextPath = request.getContextPath();
terminate.setPath(contextPath != null && contextPath.length() > 0 ? contextPath : "/");
terminate.setMaxAge(0);
response.addCookie(terminate);
%>

<c:redirect url="../../home"/>

dev/src/bitnow_client/src/main/webapp/app/myProfile/security.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="../../layouts/defaultAdminFixed.xhtml">
	<ui:define name="title">#{text['userProfile.title']}</ui:define>
	<ui:define name="body">
		<h:form id="securityForm" autocomplete="off" prependId="false">
			<div class="col-md-12">
				<p:panel id="passwordPanel" style="height: 200px;"
					header="#{text['user.password']}">
					<div class="row">
						<div class="col-md-6 form-group">
							<h:outputLabel styleClass="control-label" for="password"
								value="#{text['user.password']}" />
							<h:inputSecret styleClass="form-control"
								value="#{securityAction.user.password}" id="password"
								redisplay="true" required="true" />
						</div>
						<div class="col-md-6 form-group">
							<h:outputLabel styleClass="control-label" for="confirmPassword"
								value="#{text['user.confirmPassword']}" />
							<h:inputSecret styleClass="form-control"
								value="#{securityAction.user.confirmPassword}"
								id="confirmPassword" redisplay="true" required="true">
							</h:inputSecret>
						</div>
					</div>
					<p:spacer width="100%" height="5" />
					<div class="form-group form-actions text-right">
						<h:commandButton value="#{text['button.cancel']}"
							action="#{securityAction.cancel}" immediate="true"
							styleClass="btn btn-default" />
						<h:commandButton value="#{text['button.save']}"
							action="#{securityAction.save}" styleClass="btn btn-primary" />
					</div>
				</p:panel>
			</div>
			<p:spacer width="100%" height="10" />
			<div class="col-md-12">
				<p:panel id="twoFAPanel" style="height: 300px;"
					header="#{text['userProfile.2FA']}">
					<ui:fragment rendered="#{!securityAction.twoFAEnabled}">
						<div class="col-md-12 text-left">
							<h:outputText value="#{text['userProfile.2FA.message']}" />
							<p:spacer width="100%" height="1" />
							<p:commandButton value="#{text['button.enable']}"
								styleClass="btn btn-primary"
								update=":securityForm:enableTwoFAPanel"
								oncomplete="PF('twoFADialog').show()" />
						</div>
					</ui:fragment>
					<ui:fragment rendered="#{securityAction.twoFAEnabled}">
						<div class="col-md-12 text-left">
							<h:outputText value="#{text['userProfile.2FA.disable.message']}" />
							<p:inputText id="otpDisable"
								styleClass="input-block-level form-control" maxlength="6"
								value="#{securityAction.password2FADisable}"
								placeholder="One-Time Password">
							</p:inputText>
							<p:spacer width="100%" height="1" />
							<h:commandButton value="#{text['button.disable']}"
								action="#{securityAction.disable2FA}"
								styleClass="btn btn-primary" />
						</div>
					</ui:fragment>
				</p:panel>
				<p:dialog id="dialog1" header="#{text['userProfile.2FA']}"
					showEffect="fade" widgetVar="twoFADialog" modal="true"
					resizable="false">
					<p:outputPanel id="enableTwoFAPanel">
						<p:panelGrid>
							<p:row>
								<p:column styleClass="text-center">
									<div class="col-md-12 text-left">
										<h:outputText value="#{text['userProfile.2FA.enabling']}" />
										<br></br>
										<h:outputText value="#{text['userProfile.2FA.secret']}: " />
										<h:outputLabel value="#{securityAction.twoFAKey}" />
									</div>
								</p:column>
							</p:row>
							<p:row>
								<p:column styleClass="text-center">
									<p:graphicImage value="#{securityAction.twoFALink}"></p:graphicImage>
								</p:column>
							</p:row>
							<p:row>
								<p:column styleClass="text-right">
									<p:inputText id="otpEnable"
										styleClass="input-block-level form-control" maxlength="6"
										value="#{securityAction.password2FA}"
										placeholder="One-Time Password">
									</p:inputText>
								</p:column>
							</p:row>
							<p:row>
								<p:column styleClass="text-right">
									<h:commandButton value="#{text['button.submit']}"
										update="@form" action="#{securityAction.enable2FA}"
										styleClass="btn btn-primary"
										oncomplete="PF('twoFADialog').hide()" />
								</p:column>
							</p:row>
						</p:panelGrid>
					</p:outputPanel>
				</p:dialog>
			</div>
			<p:spacer width="100%" height="20" />
		</h:form>
	</ui:define>
</ui:composition>
</html>

dev/src/bitnow_client/src/main/webapp/app/myProfile/userForm.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="../../layouts/defaultAdminFixed.xhtml">
	<ui:define name="title">#{text['userProfile.title']}</ui:define>
	<ui:define name="body">
		<c:set var="delObject" value="#{text['userList.user']}" />
		<h:form id="userForm">
			<div class="col-md-12">
				<p:panel id="cccount" style="height: 200px;"
					header="#{text['userProfile.heading']}">
					<h:outputText value="#{text['userProfile.message']}" />
					<h:inputHidden value="#{userForm.user.id}" id="id" />
					<h:inputHidden value="#{userForm.user.version}" id="version" />
					<h:inputHidden value="#{userForm.user.password}"
						id="originalPassword" />
					<input type="hidden" name="from" value="#{userForm.from}" />
					<c:if test="${userForm.rememberMe}">
						<h:inputHidden value="#{userForm.user.password}" id="password" />
						<h:inputHidden value="#{userForm.user.confirmPassword}"
							id="confirmPassword" />
					</c:if>
					<c:if test="${empty userForm.user.version}">
						<input type="hidden" name="encryptPass" value="true" />
					</c:if>
					<div class="row">
						<div class="col-md-6 form-group">
							<h:outputLabel styleClass="control-label" for="username"
								value="#{text['user.username']}" />
							<p:inputText styleClass="form-control" required="true"
								value="#{userForm.user.username}" id="username" />
						</div>
						<div class="col-md-6 form-group">
							<h:outputLabel styleClass="control-label" for="email"
								value="#{text['user.email']}" />
							<p:inputText styleClass="form-control"
								value="#{userForm.user.email}" id="email"
								readonly="#{facesContext.currentPhaseId.ordinal eq 6}" />
						</div>
					</div>
					<c:if test="${!userForm.rememberMe}">
						<div class="row">
							<div class="col-md-6 form-group"></div>
							<div class="col-md-6 form-group">
								<h:outputLabel for="advanced" value="#{text['user.theme']}: " />
								<p:themeSwitcher id="advanced" style="width:165px" effect="fade"
									value="#{userForm.user.theme}">
									<f:selectItems value="#{userForm.themes}" />
									<h:outputText styleClass="ui-theme ui-theme-"
										style="display-block" />
								</p:themeSwitcher>
							</div>
						</div>
					</c:if>
				</p:panel>
				<ui:fragment rendered="#{!userForm.admin}">
					<p:spacer width="100%" height="10" />
					<p:panel id="ppAccount" style="height: 300px;"
						header="#{text['userProfile.ppAccount']}">
						<div class="col-md-12 text-left">
							<h:outputLabel styleClass="control-label" for="ppNumber"
								value="#{text['userProfile.ppAccount.number']}" />
							<p:inputText styleClass="form-control" required="true"
								title="#{text['userProfile.ppAccount.number.tooltip']}"
								value="#{userForm.ppAccount.number}" id="ppNumber" />
							<p:tooltip id="ppNumberTooltip" for="ppNumber" showEvent="focus"
								hideEvent="blur" />
						</div>
						<div class="col-md-6 form-group">
							<ui:fragment rendered="#{userForm.ppAccount.owner eq null}">
								<h:outputLabel styleClass="control-label" for="ppOwner"
									value="#{text['userProfile.ppAccount.owner']}" />
								<p:inputText styleClass="form-control" required="true"
									title="#{text['userProfile.ppAccount.owner.tooltip']}"
									value="#{userForm.ppAccount.owner}" id="ppOwner" />
								<p:tooltip id="ppOwnerTooltip" for="ppOwner" showEvent="focus"
									hideEvent="blur" />
							</ui:fragment>
							<ui:fragment rendered="#{userForm.ppAccount.owner ne null}">
								<h:outputLabel styleClass="control-label" for="ppOwnerReadonly"
									value="#{text['userProfile.ppAccount.owner']}" />
								<p:inputText styleClass="form-control" required="true"
									title="#{text['userProfile.ppAccount.owner.tooltip']}"
									value="#{userForm.ppAccount.owner}" id="ppOwnerReadonly"
									readonly="#{facesContext.currentPhaseId.ordinal eq 6}" />
								<p:tooltip id="ppOwnerReadonlyTooltip" for="ppOwnerReadonly"
									showEvent="focus" hideEvent="blur" />
							</ui:fragment>
						</div>
						<div class="col-md-6 form-group">
							<ui:fragment rendered="#{userForm.ppAccount.id eq null}">
								<h:outputLabel styleClass="control-label" for="ppSSN"
									value="#{text['userProfile.ppAccount.SSN']}" />
								<p:inputText styleClass="form-control" required="true"
									title="#{text['userProfile.ppAccount.SSN.tooltip']}"
									value="#{userForm.ppAccount.id}" id="ppSSN" />
								<p:tooltip id="ppSSNTooltip" for="ppSSN" showEvent="focus"
									hideEvent="blur" />
							</ui:fragment>
							<ui:fragment rendered="#{userForm.ppAccount.id ne null}">
								<h:outputLabel styleClass="control-label" for="ppSSNReadonly"
									value="#{text['userProfile.ppAccount.SSN']}" />
								<p:inputText styleClass="form-control" required="true"
									title="#{text['userProfile.ppAccount.SSN.tooltip']}"
									value="#{userForm.ppAccount.id}" id="ppSSNReadonly"
									readonly="#{facesContext.currentPhaseId.ordinal eq 6}" />
								<p:tooltip id="ppSSNReadonlyTooltip" for="ppSSNReadonly"
									showEvent="focus" hideEvent="blur" />
							</ui:fragment>
						</div>
						<div class="col-md-6 form-group">
							<h:outputLabel styleClass="control-label" for="ppWebUsername"
								value="#{text['userProfile.ppAccount.webUsername']}" />
							<p:inputText styleClass="form-control" required="true"
								title="#{text['userProfile.ppAccount.webUsername.tooltip']}"
								value="#{userForm.ppAccount.webUsername}" id="ppWebUsername" />
							<p:tooltip id="ppWebUsernameTooltip" for="ppWebUsername"
								showEvent="focus" hideEvent="blur" />
						</div>
						<div class="col-md-6 form-group">
							<h:outputLabel styleClass="control-label" for="ppWebPassword"
								value="#{text['userProfile.ppAccount.webPassword']}" />
							<p:inputText styleClass="form-control" required="true"
								title="#{text['userProfile.ppAccount.webPassword.tooltip']}"
								value="#{userForm.ppAccount.webPassword}" id="ppWebPassword" />
							<p:tooltip id="ppWebPasswordTooltip" for="ppWebPassword"
								showEvent="focus" hideEvent="blur" />
						</div>
					</p:panel>
				</ui:fragment>
				<h:panelGroup styleClass="form-group" layout="block">
					<c:if test="${not empty param['userForm:userRoles']}">
						<input type="hidden" name="userForm:userRoles"
							value="${param['userForm:userRoles']}" />
					</c:if>
					<c:forEach var="role" items="#{userForm.userRoles}"
						varStatus="status">
						<c:if test="${!status.last}">,</c:if>
						<input type="hidden" name="userForm:userRoles" value="${role}" />
					</c:forEach>
					<h:inputHidden value="#{userForm.user.enabled}" />
					<h:inputHidden value="#{userForm.user.accountExpired}" />
					<h:inputHidden value="#{userForm.user.accountLocked}" />
					<h:inputHidden value="#{userForm.user.credentialsExpired}" />
				</h:panelGroup>
				<p:spacer width="100%" height="5" />
				<div class="form-group form-actions text-right">
					<h:commandButton value="#{text['button.cancel']}"
						action="#{userForm.cancel}" immediate="true"
						styleClass="btn btn-default" />
					<h:commandButton value="#{text['button.save']}"
						action="#{userForm.save}" styleClass="btn btn-primary" />
				</div>
			</div>
			<p:spacer width="100%" height="20" />
		</h:form>
	</ui:define>
</ui:composition>
</html>